types:
    Product:
        properties:
          name: {nullable: true}
          description: {nullable: false}
          image: {range: 'Text'}
    Offer:
      properties:
        url: {nullable: false}
        price: {nullable: false, range: "Number"}
        priceCurrency: {nullable: false}